init.fs:
  /:
    bin/:
      init:
        + cargo-build: user/init
        + copy: target/_out/init
      tty:
        + cargo-build: user/tty
        + copy: target/_out/tty
      hello:
        + cargo-build: user/hello
        + copy: target/_out/hello
      ls:
        + cargo-build: user/ls
        + copy: target/_out/ls
    etc/:
      modules/:
        libhello.so:
          + cargo-build: modules/hello
          + copy: target/_out/libhello.so
        libvfs.so:
          + cargo-build: modules/vfs
          + copy: target/_out/libvfs.so
        libdev.so:
          + cargo-build: modules/dev
          + copy: target/_out/libdev.so
        libpl011.so:
          + cargo-build: modules/pl011
          + copy: target/_out/libpl011.so
        libgic_timer.so:
          + cargo-build: modules/gic-timer
          + copy: target/_out/libgic_timer.so
        libgic.so:
          + cargo-build: modules/gic
          + copy: target/_out/libgic.so
        libbcm2711_gpio.so:
          + cargo-build: modules/bcm2711-gpio
          + copy: target/_out/libbcm2711_gpio.so
      hello.txt:
        + copy-str: "Hello world from file!"
