on:
  push:
    branches:
      - main
  pull_request:
name: Unit Tests
jobs:
  test-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packages
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: codota/toolchain@v1
      - name: Install QEMU
        run: sudo apt-get install -y qemu-system
      - name: Run Unit Tests (Debug)
        run: cargo dev test
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packages
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: codota/toolchain@v1
      - name: Install QEMU
        run: sudo apt-get install -y qemu-system
      - name: Run Unit Tests (Release)
        run: cargo dev test --release
